---
theme: jekyll-theme-minimal
title: Free Breast Cancer Screening in Kenya
description: Free Breast Cancer Screening in Kenya
logo: assets/OctoberPinkRibbon.jpg
keywords: breast cancer screening
last_updated: October 14, 2020
---